### PR TITLE
snap Nodes initial release

### PR DESCRIPTION
**Pull request by bonalex01dev**
snap selected nodes to the imaginary grid of the node graph

### CODE REVIEW

**Comment by bonalex01dev** [comment]
snap selected nodes to the imaginary grid of the node graph.
This helps to get a more tidy node graph.
shortcut 'A' is set in initGui.py for quick access

**Comment by rodlie** [comment]
I'm really sorry for the delayed review, I forgot....

Could you remove the pyc files?

**Comment by bonalex01dev** [comment]
Can I remove the files from the PR or should I make a new one ? (sorry getting slooooowly up to speed with git)

**Comment by rodlie** [comment]
Just remove them from the PR with a new commit.

**Comment by bonalex01dev** [comment]
This seemed like handy manner to remove the files:
https://github.blog/changelog/2018-07-31-removing-files-from-a-pull-request/
Is it good?

**Comment by rodlie** [comment]
That might work (not tested), I'm used to the regular ``git`` cmd.

The "old" way would be:

```
cd where_you_fork_with_PR_is
git rm FILE(S)
git commit
git push
```

As long as the files are removed we are good :)

**Comment by bonalex01dev** [comment]
Thanks, will try tonight !

**Comment by bonalex01dev** [comment]
The new PR seems good to me...

**Pull request closed without merging**
